/**
 * Open Banking API
 * Latest Swagger specification for OpenBanking
 *
 * OpenAPI spec version: v2.3
 * Contact: thomas.laegler@googlemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.laegler.openbanking.api;

import com.laegler.openbanking.model.AuthorisationServerRequestSchema;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Open Banking API
 *
 * <p>Latest Swagger specification for OpenBanking
 *
 * API tests for AuthorisationServersApi 
 */
public class AuthorisationServersApiTest {


    private AuthorisationServersApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://localhost:8080/api/v1", AuthorisationServersApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Delete an Authorisation Server
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void organisationOrganisationTypeOrganisationIdAuthorisationServerAuthorisationServerIdDeleteTest() {
        String organisationType = null;
        String organisationId = null;
        String authorisationServerId = null;
        //api.organisationOrganisationTypeOrganisationIdAuthorisationServerAuthorisationServerIdDelete(organisationType, organisationId, authorisationServerId);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Get .well-known entity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void organisationOrganisationTypeOrganisationIdAuthorisationServerAuthorisationServerIdGetTest() {
        String organisationType = null;
        String organisationId = null;
        String authorisationServerId = null;
        //api.organisationOrganisationTypeOrganisationIdAuthorisationServerAuthorisationServerIdGet(organisationType, organisationId, authorisationServerId);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Update .well-known entity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void organisationOrganisationTypeOrganisationIdAuthorisationServerAuthorisationServerIdPutTest() {
        String organisationType = null;
        String organisationId = null;
        String authorisationServerId = null;
        AuthorisationServerRequestSchema authorisationServer = null;
        //api.organisationOrganisationTypeOrganisationIdAuthorisationServerAuthorisationServerIdPut(organisationType, organisationId, authorisationServerId, authorisationServer);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Get all Authorisation Servers for the given organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void organisationOrganisationTypeOrganisationIdAuthorisationServerGetTest() {
        String organisationType = null;
        String organisationId = null;
        //api.organisationOrganisationTypeOrganisationIdAuthorisationServerGet(organisationType, organisationId);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Create an Authorisation Server for the given organisation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void organisationOrganisationTypeOrganisationIdAuthorisationServerPostTest() {
        String organisationType = null;
        String organisationId = null;
        AuthorisationServerRequestSchema authorisationServer = null;
        //api.organisationOrganisationTypeOrganisationIdAuthorisationServerPost(organisationType, organisationId, authorisationServer);
        
        // TODO: test validations
        
        
    }
    
}
