/**
 * Open Banking API
 * Latest Swagger specification for OpenBanking
 *
 * OpenAPI spec version: v2.3
 * Contact: thomas.laegler@googlemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.laegler.openbanking.api;

import com.laegler.openbanking.model.OBCallbackUrl1;
import com.laegler.openbanking.model.OBCallbackUrlResponse1;
import com.laegler.openbanking.model.OBCallbackUrlsResponse1;
import com.laegler.openbanking.model.OBErrorResponse1;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Open Banking API
 *
 * <p>Latest Swagger specification for OpenBanking
 *
 * API tests for CallbackUrLsApi 
 */
public class CallbackUrLsApiTest {


    private CallbackUrLsApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://localhost:8080/api/v1", CallbackUrLsApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Delete a callback URI
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callbackUrlsCallbackUrlIdDeleteTest() {
        String callbackUrlId = null;
        String authorization = null;
        String xFapiInteractionId = null;
        //api.callbackUrlsCallbackUrlIdDelete(callbackUrlId, authorization, xFapiInteractionId);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Amend a callback URI
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callbackUrlsCallbackUrlIdPutTest() {
        String callbackUrlId = null;
        OBCallbackUrl1 obCallbackUrl1Param = null;
        String authorization = null;
        String xJwsSignature = null;
        String xFapiInteractionId = null;
        //OBCallbackUrlResponse1 response = api.callbackUrlsCallbackUrlIdPut(callbackUrlId, obCallbackUrl1Param, authorization, xJwsSignature, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Read all callback URLs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callbackUrlsGetTest() {
        String authorization = null;
        String xFapiInteractionId = null;
        //OBCallbackUrlsResponse1 response = api.callbackUrlsGet(authorization, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Create a callback URL
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callbackUrlsPostTest() {
        OBCallbackUrl1 obCallbackUrl1Param = null;
        String authorization = null;
        String xJwsSignature = null;
        String xFapiInteractionId = null;
        //OBCallbackUrlResponse1 response = api.callbackUrlsPost(obCallbackUrl1Param, authorization, xJwsSignature, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
