/**
 * Open Banking API
 * Latest Swagger specification for OpenBanking
 *
 * OpenAPI spec version: v2.3
 * Contact: thomas.laegler@googlemail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.laegler.openbanking.api;

import com.laegler.openbanking.model.OBErrorResponse1;
import com.laegler.openbanking.model.OBWritePaymentDetailsResponse1;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * Open Banking API
 *
 * <p>Latest Swagger specification for OpenBanking
 *
 * API tests for PaymentDetailsApi 
 */
public class PaymentDetailsApiTest {


    private PaymentDetailsApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://localhost:8080/open-banking/v2.3", PaymentDetailsApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDomesticPaymentsDomesticPaymentIdPaymentDetailsTest() {
        String domesticPaymentId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getDomesticPaymentsDomesticPaymentIdPaymentDetails(domesticPaymentId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDomesticScheduledPaymentsDomesticScheduledPaymentIdPaymentDetailsTest() {
        String domesticScheduledPaymentId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getDomesticScheduledPaymentsDomesticScheduledPaymentIdPaymentDetails(domesticScheduledPaymentId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDomesticStandingOrdersDomesticStandingOrderIdPaymentDetailsTest() {
        String domesticStandingOrderId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getDomesticStandingOrdersDomesticStandingOrderIdPaymentDetails(domesticStandingOrderId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFilePaymentsFilePaymentIdPaymentDetailsTest() {
        String filePaymentId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getFilePaymentsFilePaymentIdPaymentDetails(filePaymentId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInternationalPaymentsInternationalPaymentIdPaymentDetailsTest() {
        String internationalPaymentId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getInternationalPaymentsInternationalPaymentIdPaymentDetails(internationalPaymentId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInternationalScheduledPaymentsInternationalScheduledPaymentIdPaymentDetailsTest() {
        String internationalScheduledPaymentId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getInternationalScheduledPaymentsInternationalScheduledPaymentIdPaymentDetails(internationalScheduledPaymentId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Get Payment Details
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInternationalStandingOrdersInternationalStandingOrderPaymentIdPaymentDetailsTest() {
        String internationalStandingOrderPaymentId = null;
        String authorization = null;
        String xFapiAuthDate = null;
        String xFapiCustomerIpAddress = null;
        String xFapiInteractionId = null;
        //OBWritePaymentDetailsResponse1 response = api.getInternationalStandingOrdersInternationalStandingOrderPaymentIdPaymentDetails(internationalStandingOrderPaymentId, authorization, xFapiAuthDate, xFapiCustomerIpAddress, xFapiInteractionId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
